### ISSUE TITLE
Accentuation does not work

### ISSUE THREAD

**Issue by Zetat** [nwoltman/srt-to-vtt-converter#3]
Captions that have accents are not converted correctly
![esboco](https://user-images.githubusercontent.com/22025931/43502016-ef88adea-952e-11e8-8bda-78b36691e422.png)

**Comment by nwoltman** [comment]
Could you post a `.srt` file that this happens with? I tried [this file](https://github.com/nwoltman/srt-to-vtt-converter/files/2250312/subs3.srt.txt) with accents and it worked fine.
(To upload the file to GitHub, you'll need to add an extension like `.txt` to the end of the file name.)

**Comment by Zetat** [comment]
Sorry for being late. I found the problem, the error occurs when the srt file is encoded as ANSI or ISO- (any). In this case, would you like to add a validation to the program to convert to UTF8 before converting to VTT? Sorry for any error in English, Google Translator here. And congratulations on the tool, it helped me a lot.

**Comment by nwoltman** [comment]
Glad the tool has helped you 🙂
I added an option for ANSI in 527b896a7d3bfebc98016d26a9e308740f5f1d5b. Could you try the [latest executable](https://github.com/nwoltman/srt-to-vtt-converter/tree/master/dist) to see if that works for you?

**Comment by Zetat** [comment]
Worked very well. Thank you for your time. I wish all the best for you :smiley:

**Comment by nwoltman** [comment]
Thanks! I'm happy it worked 😄
